In [3]:
a = [1,2,['a','b',['Life','is']]]

In [8]:
a[2][2][0]

'Life'

In [5]:
%%timeit
inputA = [1,2,3,4,5,6,7,8,9,10]
inputB = [1,2,3,4,5,6,7,8,9,10]
inputC = []
for i in range(len(inputA)):
    inputC.append(inputA[i]*inputB[i])

1.6 µs ± 36.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
import numpy as np

In [11]:
inputA=np.array(range(1,11))
inputB=np.array(range(1,11))
inputC=inputA*inputB

In [12]:
inputC

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [15]:
np.random.seed(42)
arr2 = np.random.randint(1,10,(3,4))
arr2

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8]])

In [16]:
np.sum(arr2)

74

In [18]:
arr2.sum()

74

In [20]:
np.sum(arr2, axis = 0)

array([19, 11, 23, 21])

In [21]:
np.sum(arr2, axis = 1)

array([24, 25, 25])

In [33]:
np.random.seed(42)
x = np.random.randint(1,20,(4,4))
x

array([[ 7, 15, 11,  8],
       [ 7, 19, 11, 11],
       [ 4,  8,  3,  2],
       [12,  6,  2,  1]])

In [34]:
(x>5) & (x<10)

array([[ True, False, False,  True],
       [ True, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False]])

In [35]:
x[(x>5) & (x<10)]

array([7, 8, 7, 8, 6])

In [36]:
np.sum((x>5) & (x<10), axis =1)

array([2, 1, 1, 1])

In [37]:
x = np.arange(20).reshape(4,5)

In [38]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
x = np.arange(50).reshape(-1,10)

In [40]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
x[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
x[1][2:6]

array([12, 13, 14, 15])

In [47]:
x[1][[1,2,5,6]]

array([11, 12, 15, 16])

In [48]:
x[1,1:5]

array([11, 12, 13, 14])

In [61]:
np.random.seed(11)
x = np.array(np.random.randint(20, size=5))

In [62]:
x

array([16, 17, 13, 12,  1])

In [63]:
idx = np.argsort(x)

In [64]:
idx

array([4, 3, 2, 0, 1], dtype=int64)

In [66]:
for i in idx:
    print(x[i], end=' ')

1 12 13 16 17 

In [67]:
x[idx]

array([ 1, 12, 13, 16, 17])

In [68]:
ar = np.arange(6).reshape(2,3)

In [69]:
ar, ar.shape

(array([[0, 1, 2],
        [3, 4, 5]]), (2, 3))

In [70]:
ar.T, ar.T.shape

(array([[0, 3],
        [1, 4],
        [2, 5]]), (3, 2))

In [71]:
#ar 행렬곱 ar.T ar*ar.T 합성곱가능 결과는 정방행렬(n*n)

In [73]:
np.dot(ar, ar.T)

array([[ 5, 14],
       [14, 50]])

In [74]:
np.dot(ar, ar.T).shape

(2, 2)

In [75]:
x = np.arange(1,10,0.1).reshape(10,-1)

In [76]:
x

array([[1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8],
       [1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7],
       [2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
       [3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5],
       [4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4],
       [5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3],
       [6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2],
       [7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1],
       [8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ],
       [9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [78]:
x.shape

(10, 9)

In [82]:
np.random.seed(42)
ar = np.random.random((3,5,6))

In [83]:
ar

array([[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
         0.15599452],
        [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
         0.96990985],
        [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
         0.52475643],
        [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
         0.36636184],
        [0.45606998, 0.78517596, 0.19967378, 0.51423444, 0.59241457,
         0.04645041]],

       [[0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
         0.80839735],
        [0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823,
         0.49517691],
        [0.03438852, 0.9093204 , 0.25877998, 0.66252228, 0.31171108,
         0.52006802],
        [0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894,
         0.89482735],
        [0.59789998, 0.92187424, 0.0884925 , 0.19598286, 0.04522729,
         0.32533033]],

       [[0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
         0.542696

In [84]:
np.argmin(ar)

72

In [85]:
np.argmax(ar)

69

In [86]:
np.min(ar)

0.005522117123602399

In [87]:
np.max(ar)

0.9868869366005173